# Generated by Django 3.0.10 on 2024-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("motor_type", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RobotRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("robot_id", models.TextField(blank=True, null=True)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("finished", models.DateTimeField(auto_now_add=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
