# Generated by Django 3.0.10 on 2024-01-09 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Robot",
            new_name="RobotTemp",
        ),
    ]
