# Generated by Django 5.0.1 on 2024-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_auto_20240109_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotrun",
            name="distance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="robotrun",
            name="finished",
            field=models.DateTimeField(default=""),
        ),
        migrations.AlterField(
            model_name="robotrun",
            name="robot_id",
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name="robotrun",
            name="started",
            field=models.DateTimeField(default=""),
        ),
        migrations.AlterField(
            model_name="robotrun",
            name="status",
            field=models.TextField(default=""),
        ),
    ]
