# Generated by Django 5.0.1 on 2024-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_robotrun_distance_alter_robotrun_finished_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="robotrun",
            options={"ordering": ["distance"]},
        ),
        migrations.AlterField(
            model_name="robotrun",
            name="robot_id",
            field=models.IntegerField(default=0),
        ),
    ]
