# Generated by Django 5.0.1 on 2024-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_robotrun_options_alter_robotrun_robot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="motor_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="robot",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
