# Generated by Django 5.0.1 on 2024-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_robot_motor_type_alter_robot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="motor_type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="robot",
            name="name",
            field=models.TextField(),
        ),
    ]
