# Generated by Django 5.0.1 on 2024-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_robot_motor_type_alter_robot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="motor_type",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="robot",
            name="name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
