# Generated by Django 5.0.1 on 2024-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_robotrun_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="next_run",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
