# Generated by Django 5.0.1 on 2024-01-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_robot_next_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="next_run",
            field=models.DateTimeField(null=True),
        ),
    ]
