apiVersion: apps/v1
kind: Deployment
metadata:
  name: generative-ai
  labels:
    app: generative-ai
    group: generative-ai-services
    team: generative-ai-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generative-ai
  template:
    metadata:
      labels:
        app: generative-ai
        group: generative-ai-services
        team: generative-ai-team
        networking/access-redis-cache: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: generative-ai-container
        image: gcr.io/artificial-intelligence/generative_ai:${BUILD_TAG}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"