apiVersion: v1
kind: Secret
metadata:
  name: generative-ai-credentials
  labels:
    app: generative-ai
    group: generative-ai-services
    team: generative-ai-team
type: Opaque
data:
  OPENAI_API_KEY: ${OPENAI_API_KEY}