apiVersion: v1
kind: Secret
metadata:
  name: generative-ai-credentials
  labels:  # categorizing k8s resources
    app: generative-ai
    group: generative-ai-services
    team: generative-ai-team
type: Opaque  # key-value pairs
data:
  OPENAI_API_KEY: ${OPENAI_API_KEY}