apiVersion: v1
kind: Service
metadata:
  name: generative-ai-service
  labels:  # categorizing k8s resources
    app: generative-ai
    group: generative-ai-services
    team: generative-ai-team
spec:
  selector:  # route traffic to specific Pods
    app: generative-ai
  type: ClusterIP
  ClusterIP: None
  ports:
    - name: http
      port: 8080  # port exposed by the Service
      targetPort: 8080  # port on the Pods