name: Django Frontend App Tests

on: [push, pull_request]

jobs:
  django-frontend-app-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django==3.0.10
        pip install SQLAlchemy==2.0.25
        pip install python-dotenv==1.0.0
        pip install psycopg2==2.9.9

    - name: Django Frontend App Tests
      run: |
        python computer-vision/robot-object-recognition/src/python/frontend_app/manage.py test