name: Django Frontend App Tests

on: [push, pull_request]

jobs:
  django-frontend-app-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django==3.0.10

    - name: Django Frontend App Tests
      run: |
        python manage.py test