name: Generative AI

on:
  push:
    paths:
      - 'generative_ai/**'
  pull_request:
    paths:
      - 'generative_ai/**'

env:
  PYTHON_VERSION: "3.11"

jobs:
  common:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  static-analysis:
    runs-on: ubuntu-22.04
    needs: common
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0 flake8==7.1.1 mypy==1.13.0

      - name: Formatter
        run: |
          black generative_ai

      - name: Type Checker
        run: |
          mypy generative_ai

      - name: Linter
        run: |
          flake8 generative_ai

  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==4.23.2

      - name: Test articles
        run: |
          cd generative_ai && tox -c tox.ini -e test_articles

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}