name: Static Analysis Check

on: [push, pull_request]

jobs:
  static-analysis-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0

      - name: Static Analysis Formatting
        run: |
          black --check computer-vision/robot-object-recognition/src/python/fontend_app
